version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
  settings:
    misspell:
      locale: UK
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: indent-error-flow
        - name: range
        - name: superfluous-else
        - name: unreachable-code

formatters:
  enable:
    - gofmt
    - goimports
